# Generated by Django 3.0.4 on 2020-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionpost',
            name='image',
            field=models.ImageField(default='postdefault.jpg', upload_to='images/'),
        ),
    ]
