# Generated by Django 3.0.4 on 2020-04-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20200421_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionpost',
            name='image',
            field=models.ImageField(default='/static/images/postdefault.jpg', upload_to='images/'),
        ),
    ]
