# Generated by Django 2.2 on 2020-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='funnypost',
            name='categories',
            field=models.ManyToManyField(to='funny.Category'),
        ),
    ]
