# Generated by Django 2.2 on 2020-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0002_auto_20200408_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funnypost',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
