# Generated by Django 3.0.4 on 2020-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0003_auto_20200408_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnypost',
            name='image',
            field=models.ImageField(default='/static/images/postdefault.jpg', upload_to='images/'),
        ),
    ]
