# Generated by Django 2.2 on 2020-04-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='l_name',
        ),
    ]
