# Generated by Django 2.2 on 2020-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
